---

# Workaround for https://github.com/ansible/ansible-modules-extras/issues/471
- name: Install Yum Utilities
  shell: dnf -y install yum-utils
  args:
    creates: /usr/bin/repoquery
  when: is_fedora

- name: Install Node.js on Fedora
  dnf:
    name: "{{ nodejs_fedora_rpms[nodejs_version] }}"
    state: present
  when: is_fedora

- name: Install additional RPM packages on Fedora
  dnf:
    name: "{{ item }}"
    state: latest
  with_flattened:
    - "{{ nodejs_rpm_packages }}"
    - "{{ nodejs_app_rpm_packages }}"
  when: is_fedora

- name: Install Node.js on CentOS
  yum:
    name: "{{ nodejs_centos_rpms[nodejs_version] }}"
    state: present
  when: is_centos

- name: Fail if nodejs- RPM packages are specified in nodejs_app_rpm_packages
  fail:
    msg: "Node.js packages should be installed through npm (see nodejs_app_npm_packages)"
  when: "'nodejs-' in {{ nodejs_app_rpm_packages|join(' ') }}"

- name: Install additional RPM packages on CentOS
  yum:
    name: "{{ item }}"
    state: latest
  with_flattened:
    - "{{ nodejs_rpm_packages }}"
    - "{{ nodejs_app_rpm_packages }}"
  when: is_centos

- name: Adjust npm version
  npm:
    name: npm
    version: "{{ nodejs_npm_version }}"
    global: yes
  when: nodejs_npm_version is defined

- name: Install required npm packages
  npm:
    name: "{{ item }}"
    global: yes
  with_items:
    - "{{ nodejs_npm_packages }}"
    - "{{ nodejs_app_npm_packages }}"

- name: Install nodemon if a development environment is being used
  npm:
    name: nodemon
    state: present
    global: yes
  when: nodejs_app_dev_env
